export interface CountryData {
  value: string;
  label: string;
  phoneCode: string;
  phoneLength: number;
  inputFormat: string;
}

// Country flag image URL generator
export const getCountryFlagUrl = (countryCode: string): string => {
  return `https://flagcdn.com/w40/${countryCode.toLowerCase()}.png`;
};

const allCountries: CountryData[] = [
  { value: "AF", label: "Afghanistan", phoneCode: "+93", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "AL", label: "Albania", phoneCode: "+355", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "DZ", label: "Algeria", phoneCode: "+213", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "AS", label: "American Samoa", phoneCode: "+1-684", phoneLength: 7, inputFormat: "### ####" },
  { value: "AD", label: "Andorra", phoneCode: "+376", phoneLength: 6, inputFormat: "### ###" },
  { value: "AO", label: "Angola", phoneCode: "+244", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "AI", label: "Anguilla", phoneCode: "+1-264", phoneLength: 7, inputFormat: "### ####" },
  { value: "AG", label: "Antigua and Barbuda", phoneCode: "+1-268", phoneLength: 7, inputFormat: "### ####" },
  { value: "AR", label: "Argentina", phoneCode: "+54", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "AM", label: "Armenia", phoneCode: "+374", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "AW", label: "Aruba", phoneCode: "+297", phoneLength: 7, inputFormat: "### ####" },
  { value: "AU", label: "Australia", phoneCode: "+61", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "AT", label: "Austria", phoneCode: "+43", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "AZ", label: "Azerbaijan", phoneCode: "+994", phoneLength: 9, inputFormat: "## ### ## ##" },
  { value: "BS", label: "Bahamas", phoneCode: "+1-242", phoneLength: 7, inputFormat: "### ####" },
  { value: "BH", label: "Bahrain", phoneCode: "+973", phoneLength: 8, inputFormat: "#### ####" },
  { value: "BD", label: "Bangladesh", phoneCode: "+880", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "BB", label: "Barbados", phoneCode: "+1-246", phoneLength: 7, inputFormat: "### ####" },
  { value: "BY", label: "Belarus", phoneCode: "+375", phoneLength: 9, inputFormat: "## ### ## ##" },
  { value: "BE", label: "Belgium", phoneCode: "+32", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "BZ", label: "Belize", phoneCode: "+501", phoneLength: 7, inputFormat: "### ####" },
  { value: "BJ", label: "Benin", phoneCode: "+229", phoneLength: 9, inputFormat: "## ### ###" },
  { value: "BM", label: "Bermuda", phoneCode: "+1-441", phoneLength: 7, inputFormat: "### ####" },
  { value: "BT", label: "Bhutan", phoneCode: "+975", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "BO", label: "Bolivia", phoneCode: "+591", phoneLength: 8, inputFormat: "### #####" },
  { value: "BA", label: "Bosnia and Herzegovina", phoneCode: "+387", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "BW", label: "Botswana", phoneCode: "+267", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "BR", label: "Brazil", phoneCode: "+55", phoneLength: 11, inputFormat: "## ##### ####" },
  { value: "IO", label: "British Indian Ocean Territory", phoneCode: "+246", phoneLength: 7, inputFormat: "### ####" },
  { value: "VG", label: "British Virgin Islands", phoneCode: "+1-284", phoneLength: 7, inputFormat: "### ####" },
  { value: "BN", label: "Brunei", phoneCode: "+673", phoneLength: 7, inputFormat: "### ####" },
  { value: "BG", label: "Bulgaria", phoneCode: "+359", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "BF", label: "Burkina Faso", phoneCode: "+226", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "BI", label: "Burundi", phoneCode: "+257", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "KH", label: "Cambodia", phoneCode: "+855", phoneLength: 9, inputFormat: "## ### ###" },
  { value: "CM", label: "Cameroon", phoneCode: "+237", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "CA", label: "Canada", phoneCode: "+1", phoneLength: 10, inputFormat: "(###) ### ####" },
  { value: "CV", label: "Cape Verde", phoneCode: "+238", phoneLength: 7, inputFormat: "### ####" },
  { value: "KY", label: "Cayman Islands", phoneCode: "+1-345", phoneLength: 7, inputFormat: "### ####" },
  { value: "CF", label: "Central African Republic", phoneCode: "+236", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "TD", label: "Chad", phoneCode: "+235", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "CL", label: "Chile", phoneCode: "+56", phoneLength: 9, inputFormat: "# #### ####" },
  { value: "CN", label: "China", phoneCode: "+86", phoneLength: 11, inputFormat: "### #### ####" },
  { value: "CX", label: "Christmas Island", phoneCode: "+61", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "CC", label: "Cocos Islands", phoneCode: "+61", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "CO", label: "Colombia", phoneCode: "+57", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "KM", label: "Comoros", phoneCode: "+269", phoneLength: 7, inputFormat: "### ####" },
  { value: "CK", label: "Cook Islands", phoneCode: "+682", phoneLength: 5, inputFormat: "## ###" },
  { value: "CR", label: "Costa Rica", phoneCode: "+506", phoneLength: 8, inputFormat: "#### ####" },
  { value: "HR", label: "Croatia", phoneCode: "+385", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "CU", label: "Cuba", phoneCode: "+53", phoneLength: 8, inputFormat: "#### ####" },
  { value: "CW", label: "Curaçao", phoneCode: "+599", phoneLength: 7, inputFormat: "### ####" },
  { value: "CY", label: "Cyprus", phoneCode: "+357", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "CZ", label: "Czech Republic", phoneCode: "+420", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "CD", label: "Democratic Republic of the Congo", phoneCode: "+243", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "DK", label: "Denmark", phoneCode: "+45", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "DJ", label: "Djibouti", phoneCode: "+253", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "DM", label: "Dominica", phoneCode: "+1-767", phoneLength: 7, inputFormat: "### ####" },
  { value: "DO", label: "Dominican Republic", phoneCode: "+1-809", phoneLength: 10, inputFormat: "(###) ### ####" },
  { value: "EC", label: "Ecuador", phoneCode: "+593", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "EG", label: "Egypt", phoneCode: "+20", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "SV", label: "El Salvador", phoneCode: "+503", phoneLength: 8, inputFormat: "#### ####" },
  { value: "GQ", label: "Equatorial Guinea", phoneCode: "+240", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "ER", label: "Eritrea", phoneCode: "+291", phoneLength: 7, inputFormat: "# ### ###" },
  { value: "EE", label: "Estonia", phoneCode: "+372", phoneLength: 8, inputFormat: "### ####" },
  { value: "ET", label: "Ethiopia", phoneCode: "+251", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "FK", label: "Falkland Islands", phoneCode: "+500", phoneLength: 5, inputFormat: "#####" },
  { value: "FO", label: "Faroe Islands", phoneCode: "+298", phoneLength: 5, inputFormat: "#####" },
  { value: "FJ", label: "Fiji", phoneCode: "+679", phoneLength: 7, inputFormat: "### ####" },
  { value: "FI", label: "Finland", phoneCode: "+358", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "FR", label: "France", phoneCode: "+33", phoneLength: 9, inputFormat: "# ## ## ## ##" },
  { value: "PF", label: "French Polynesia", phoneCode: "+689", phoneLength: 6, inputFormat: "## ## ##" },
  { value: "GA", label: "Gabon", phoneCode: "+241", phoneLength: 7, inputFormat: "## ## ##" },
  { value: "GM", label: "Gambia", phoneCode: "+220", phoneLength: 7, inputFormat: "### ####" },
  { value: "GE", label: "Georgia", phoneCode: "+995", phoneLength: 9, inputFormat: "### ## ## ##" },
  { value: "DE", label: "Germany", phoneCode: "+49", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "GH", label: "Ghana", phoneCode: "+233", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "GI", label: "Gibraltar", phoneCode: "+350", phoneLength: 8, inputFormat: "### #####" },
  { value: "GR", label: "Greece", phoneCode: "+30", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "GL", label: "Greenland", phoneCode: "+299", phoneLength: 6, inputFormat: "## ## ##" },
  { value: "GD", label: "Grenada", phoneCode: "+1-473", phoneLength: 7, inputFormat: "### ####" },
  { value: "GU", label: "Guam", phoneCode: "+1-671", phoneLength: 7, inputFormat: "### ####" },
  { value: "GT", label: "Guatemala", phoneCode: "+502", phoneLength: 8, inputFormat: "#### ####" },
  { value: "GG", label: "Guernsey", phoneCode: "+44-1481", phoneLength: 6, inputFormat: "## ## ##" },
  { value: "GN", label: "Guinea", phoneCode: "+224", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "GW", label: "Guinea-Bissau", phoneCode: "+245", phoneLength: 7, inputFormat: "### ####" },
  { value: "GY", label: "Guyana", phoneCode: "+592", phoneLength: 7, inputFormat: "### ####" },
  { value: "HT", label: "Haiti", phoneCode: "+509", phoneLength: 8, inputFormat: "## ## ####" },
  { value: "HN", label: "Honduras", phoneCode: "+504", phoneLength: 8, inputFormat: "#### ####" },
  { value: "HK", label: "Hong Kong", phoneCode: "+852", phoneLength: 8, inputFormat: "#### ####" },
  { value: "HU", label: "Hungary", phoneCode: "+36", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "IS", label: "Iceland", phoneCode: "+354", phoneLength: 7, inputFormat: "### ####" },
  { value: "IN", label: "India", phoneCode: "+91", phoneLength: 10, inputFormat: "#### ### ###" },
  { value: "ID", label: "Indonesia", phoneCode: "+62", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "IR", label: "Iran", phoneCode: "+98", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "IQ", label: "Iraq", phoneCode: "+964", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "IE", label: "Ireland", phoneCode: "+353", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "IM", label: "Isle of Man", phoneCode: "+44-1624", phoneLength: 6, inputFormat: "### ###" },
  { value: "IL", label: "Israel", phoneCode: "+972", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "IT", label: "Italy", phoneCode: "+39", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "CI", label: "Ivory Coast", phoneCode: "+225", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "JM", label: "Jamaica", phoneCode: "+1-876", phoneLength: 7, inputFormat: "### ####" },
  { value: "JP", label: "Japan", phoneCode: "+81", phoneLength: 10, inputFormat: "## #### ####" },
  { value: "JE", label: "Jersey", phoneCode: "+44-1534", phoneLength: 6, inputFormat: "### ###" },
  { value: "JO", label: "Jordan", phoneCode: "+962", phoneLength: 9, inputFormat: "# ### ####" },
  { value: "KZ", label: "Kazakhstan", phoneCode: "+7", phoneLength: 10, inputFormat: "### ### ## ##" },
  { value: "KE", label: "Kenya", phoneCode: "+254", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "KI", label: "Kiribati", phoneCode: "+686", phoneLength: 5, inputFormat: "#####" },
  { value: "XK", label: "Kosovo", phoneCode: "+383", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "KW", label: "Kuwait", phoneCode: "+965", phoneLength: 8, inputFormat: "#### ####" },
  { value: "KG", label: "Kyrgyzstan", phoneCode: "+996", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "LA", label: "Laos", phoneCode: "+856", phoneLength: 9, inputFormat: "## ### ###" },
  { value: "LV", label: "Latvia", phoneCode: "+371", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "LB", label: "Lebanon", phoneCode: "+961", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "LS", label: "Lesotho", phoneCode: "+266", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "LR", label: "Liberia", phoneCode: "+231", phoneLength: 7, inputFormat: "## ### ##" },
  { value: "LY", label: "Libya", phoneCode: "+218", phoneLength: 10, inputFormat: "## ### ####" },
  { value: "LI", label: "Liechtenstein", phoneCode: "+423", phoneLength: 7, inputFormat: "### ####" },
  { value: "LT", label: "Lithuania", phoneCode: "+370", phoneLength: 8, inputFormat: "### #####" },
  { value: "LU", label: "Luxembourg", phoneCode: "+352", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "MO", label: "Macau", phoneCode: "+853", phoneLength: 8, inputFormat: "#### ####" },
  { value: "MK", label: "North Macedonia", phoneCode: "+389", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "MG", label: "Madagascar", phoneCode: "+261", phoneLength: 9, inputFormat: "## ## ### ##" },
  { value: "MW", label: "Malawi", phoneCode: "+265", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "MY", label: "Malaysia", phoneCode: "+60", phoneLength: 10, inputFormat: "## ### ####" },
  { value: "MV", label: "Maldives", phoneCode: "+960", phoneLength: 7, inputFormat: "### ####" },
  { value: "ML", label: "Mali", phoneCode: "+223", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "MT", label: "Malta", phoneCode: "+356", phoneLength: 8, inputFormat: "#### ####" },
  { value: "MH", label: "Marshall Islands", phoneCode: "+692", phoneLength: 7, inputFormat: "### ####" },
  { value: "MR", label: "Mauritania", phoneCode: "+222", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "MU", label: "Mauritius", phoneCode: "+230", phoneLength: 8, inputFormat: "#### ####" },
  { value: "YT", label: "Mayotte", phoneCode: "+262", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "MX", label: "Mexico", phoneCode: "+52", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "FM", label: "Micronesia", phoneCode: "+691", phoneLength: 7, inputFormat: "### ####" },
  { value: "MD", label: "Moldova", phoneCode: "+373", phoneLength: 8, inputFormat: "### ## ###" },
  { value: "MC", label: "Monaco", phoneCode: "+377", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "MN", label: "Mongolia", phoneCode: "+976", phoneLength: 8, inputFormat: "#### ####" },
  { value: "ME", label: "Montenegro", phoneCode: "+382", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "MS", label: "Montserrat", phoneCode: "+1-664", phoneLength: 7, inputFormat: "### ####" },
  { value: "MA", label: "Morocco", phoneCode: "+212", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "MZ", label: "Mozambique", phoneCode: "+258", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "MM", label: "Myanmar", phoneCode: "+95", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "NA", label: "Namibia", phoneCode: "+264", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "NR", label: "Nauru", phoneCode: "+674", phoneLength: 7, inputFormat: "### ####" },
  { value: "NP", label: "Nepal", phoneCode: "+977", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "NL", label: "Netherlands", phoneCode: "+31", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "NC", label: "New Caledonia", phoneCode: "+687", phoneLength: 6, inputFormat: "## ## ##" },
  { value: "NZ", label: "New Zealand", phoneCode: "+64", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "NI", label: "Nicaragua", phoneCode: "+505", phoneLength: 8, inputFormat: "#### ####" },
  { value: "NE", label: "Niger", phoneCode: "+227", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "NG", label: "Nigeria", phoneCode: "+234", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "NU", label: "Niue", phoneCode: "+683", phoneLength: 4, inputFormat: "####" },
  { value: "KP", label: "North Korea", phoneCode: "+850", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "MP", label: "Northern Mariana Islands", phoneCode: "+1-670", phoneLength: 7, inputFormat: "### ####" },
  { value: "NO", label: "Norway", phoneCode: "+47", phoneLength: 8, inputFormat: "### ## ###" },
  { value: "OM", label: "Oman", phoneCode: "+968", phoneLength: 8, inputFormat: "#### ####" },
  { value: "PK", label: "Pakistan", phoneCode: "+92", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "PW", label: "Palau", phoneCode: "+680", phoneLength: 7, inputFormat: "### ####" },
  { value: "PS", label: "Palestine", phoneCode: "+970", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "PA", label: "Panama", phoneCode: "+507", phoneLength: 8, inputFormat: "### ####" },
  { value: "PG", label: "Papua New Guinea", phoneCode: "+675", phoneLength: 8, inputFormat: "### ####" },
  { value: "PY", label: "Paraguay", phoneCode: "+595", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "PE", label: "Peru", phoneCode: "+51", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "PH", label: "Philippines", phoneCode: "+63", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "PL", label: "Poland", phoneCode: "+48", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "PT", label: "Portugal", phoneCode: "+351", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "PR", label: "Puerto Rico", phoneCode: "+1-787", phoneLength: 10, inputFormat: "(###) ### ####" },
  { value: "QA", label: "Qatar", phoneCode: "+974", phoneLength: 8, inputFormat: "#### ####" },
  { value: "CG", label: "Republic of the Congo", phoneCode: "+242", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "RO", label: "Romania", phoneCode: "+40", phoneLength: 10, inputFormat: "### ### ####" },
  { value: "RU", label: "Russia", phoneCode: "+7", phoneLength: 10, inputFormat: "(###) ### ####" },
  { value: "RW", label: "Rwanda", phoneCode: "+250", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "BL", label: "Saint Barthélemy", phoneCode: "+590", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "SH", label: "Saint Helena", phoneCode: "+290", phoneLength: 4, inputFormat: "####" },
  { value: "KN", label: "Saint Kitts and Nevis", phoneCode: "+1-869", phoneLength: 7, inputFormat: "### ####" },
  { value: "LC", label: "Saint Lucia", phoneCode: "+1-758", phoneLength: 7, inputFormat: "### ####" },
  { value: "MF", label: "Saint Martin", phoneCode: "+590", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "PM", label: "Saint Pierre and Miquelon", phoneCode: "+508", phoneLength: 6, inputFormat: "## ## ##" },
  { value: "VC", label: "Saint Vincent and the Grenadines", phoneCode: "+1-784", phoneLength: 7, inputFormat: "### ####" },
  { value: "WS", label: "Samoa", phoneCode: "+685", phoneLength: 7, inputFormat: "### ####" },
  { value: "SM", label: "San Marino", phoneCode: "+378", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "ST", label: "São Tomé and Príncipe", phoneCode: "+239", phoneLength: 7, inputFormat: "### ####" },
  { value: "SA", label: "Saudi Arabia", phoneCode: "+966", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "SN", label: "Senegal", phoneCode: "+221", phoneLength: 9, inputFormat: "## ### ## ##" },
  { value: "RS", label: "Serbia", phoneCode: "+381", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "SC", label: "Seychelles", phoneCode: "+248", phoneLength: 7, inputFormat: "# ### ###" },
  { value: "SL", label: "Sierra Leone", phoneCode: "+232", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "SG", label: "Singapore", phoneCode: "+65", phoneLength: 8, inputFormat: "#### ####" },
  { value: "SX", label: "Sint Maarten", phoneCode: "+1-721", phoneLength: 7, inputFormat: "### ####" },
  { value: "SK", label: "Slovakia", phoneCode: "+421", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "SI", label: "Slovenia", phoneCode: "+386", phoneLength: 9, inputFormat: "## ### ###" },
  { value: "SB", label: "Solomon Islands", phoneCode: "+677", phoneLength: 7, inputFormat: "### ####" },
  { value: "SO", label: "Somalia", phoneCode: "+252", phoneLength: 9, inputFormat: "## ### ###" },
  { value: "ZA", label: "South Africa", phoneCode: "+27", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "KR", label: "South Korea", phoneCode: "+82", phoneLength: 10, inputFormat: "## #### ####" },
  { value: "SS", label: "South Sudan", phoneCode: "+211", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "ES", label: "Spain", phoneCode: "+34", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "LK", label: "Sri Lanka", phoneCode: "+94", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "SD", label: "Sudan", phoneCode: "+249", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "SR", label: "Suriname", phoneCode: "+597", phoneLength: 7, inputFormat: "### ####" },
  { value: "SZ", label: "Eswatini", phoneCode: "+268", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "SE", label: "Sweden", phoneCode: "+46", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "CH", label: "Switzerland", phoneCode: "+41", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "SY", label: "Syria", phoneCode: "+963", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "TW", label: "Taiwan", phoneCode: "+886", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "TJ", label: "Tajikistan", phoneCode: "+992", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "TZ", label: "Tanzania", phoneCode: "+255", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "TH", label: "Thailand", phoneCode: "+66", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "TL", label: "Timor-Leste", phoneCode: "+670", phoneLength: 7, inputFormat: "### ####" },
  { value: "TG", label: "Togo", phoneCode: "+228", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "TK", label: "Tokelau", phoneCode: "+690", phoneLength: 4, inputFormat: "####" },
  { value: "TO", label: "Tonga", phoneCode: "+676", phoneLength: 5, inputFormat: "#####" },
  { value: "TT", label: "Trinidad and Tobago", phoneCode: "+1-868", phoneLength: 7, inputFormat: "### ####" },
  { value: "TN", label: "Tunisia", phoneCode: "+216", phoneLength: 8, inputFormat: "## ### ###" },
  { value: "TR", label: "Turkey", phoneCode: "+90", phoneLength: 10, inputFormat: "(###) ### ####" },
  { value: "TM", label: "Turkmenistan", phoneCode: "+993", phoneLength: 8, inputFormat: "## ## ## ##" },
  { value: "TC", label: "Turks and Caicos Islands", phoneCode: "+1-649", phoneLength: 7, inputFormat: "### ####" },
  { value: "TV", label: "Tuvalu", phoneCode: "+688", phoneLength: 5, inputFormat: "#####" },
  { value: "VI", label: "U.S. Virgin Islands", phoneCode: "+1-340", phoneLength: 7, inputFormat: "### ####" },
  { value: "UG", label: "Uganda", phoneCode: "+256", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "UA", label: "Ukraine", phoneCode: "+380", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "AE", label: "United Arab Emirates", phoneCode: "+971", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "GB", label: "United Kingdom", phoneCode: "+44", phoneLength: 10, inputFormat: "(###) ### ####" },
  { value: "US", label: "United States", phoneCode: "+1", phoneLength: 10, inputFormat: "(###) ### ####" },
  { value: "UY", label: "Uruguay", phoneCode: "+598", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "UZ", label: "Uzbekistan", phoneCode: "+998", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "VU", label: "Vanuatu", phoneCode: "+678", phoneLength: 7, inputFormat: "### ####" },
  { value: "VA", label: "Vatican City", phoneCode: "+379", phoneLength: 6, inputFormat: "## ### ###" },
  { value: "VE", label: "Venezuela", phoneCode: "+58", phoneLength: 10, inputFormat: "(###) ### ####" },
  { value: "VN", label: "Vietnam", phoneCode: "+84", phoneLength: 9, inputFormat: "## ### ####" },
  { value: "WF", label: "Wallis and Futuna", phoneCode: "+681", phoneLength: 6, inputFormat: "## ### ###" },
  { value: "EH", label: "Western Sahara", phoneCode: "+212", phoneLength: 9, inputFormat: "## ### ###" },
  { value: "YE", label: "Yemen", phoneCode: "+967", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "ZM", label: "Zambia", phoneCode: "+260", phoneLength: 9, inputFormat: "### ### ###" },
  { value: "ZW", label: "Zimbabwe", phoneCode: "+263", phoneLength: 9, inputFormat: "### ### ###" },
];

export { allCountries };
export default allCountries;
