export interface ChainModel {
  __v: number;
  _id: string;
  chainId: number;
  createdAt: string;
  explorerUrl: string;
  isEVM: boolean;
  name: string;
  nativeCurrencyId: {
    __v: number;
    _id: string;
    ath: number;
    buyRate: number;
    circulatingSupply: number;
    code: string;
    createdAt: string;
    defaultNewsProvider: string;
    defaultRatesProvider: string;
    isActive: boolean;
    isCrypto: boolean;
    isStable: boolean;
    isUserToken: boolean;
    logo: string;
    maxSupply: number;
    name: string;
    preferredNewsProviders: string[];
    preferredRatesProviders: string[];
    preferredTokenMetricsProviders: string[];
    sellRate: number;
    symbol: string;
    totalSupply: number;
    updatedAt: string;
    volatility: number;
  };
  nativeCurrencySymbol: string;
  rpcUrl: string;
  symbol: string;
  updatedAt: string;
}
