export const WALLET_GROUP_CLASS = {
  PRIVATE_KEY: "PRIVATE_KEY",
  SEEDPHRASE: "SEEDPHRASE",
  WATCH: "WATCH"
}

export const WALLET_GROUP_TYPE = {
  GENERATED: "GENERATED",
  IMPORT: "IMPORT",
  WATCH: "WATCH"
}