import React from "react";
import FullPageModalWrapper from "./FullPaperModalWrapper";
import Box from "../general/Box";
import { Image } from "expo-image";
import CustomButton from "../general/CustomButton";
import CustomText from "../general/CustomText";
import { useTheme } from "@shopify/restyle";
import { Theme } from "@/theme";
import useActiveTheme from "@/hooks/useTheme";
import { ScrollView } from "react-native-gesture-handler";

const OnboardingInformationModal = ({
  isOpen,
  onClose,
  type,
}: {
  isOpen: boolean;
  onClose: () => void;
  type: "SeedPhrase" | "Wallet" | "PrivateKey";
}) => {
  const theme = useTheme<Theme>();
  const { colorTheme: activeTheme } = useActiveTheme();
  const handleImage = () => {
    switch (type) {
      case "PrivateKey": {
        return require("@/assets/images/lock.png");
      }
      case "SeedPhrase": {
        return require("@/assets/images/lock.png");
      }
      case "Wallet": {
        return require("@/assets/images/vault.png");
      }
    }
  };

  const handleTitle = () => {
    switch (type) {
      case "PrivateKey": {
        return "What's a Private Key";
      }
      case "SeedPhrase": {
        return "What's a Seed Phrase";
      }
      case "Wallet": {
        return "What's a Wallet";
      }
    }
  };

  const handleBodyText = () => {
    switch (type) {
      case "PrivateKey": {
        return (
          <>
            <CustomText variant="body" mt="l">
              This is a 64-character cryptographic key that grants you access to
              an individual wallet address and its contained assets.
            </CustomText>
            <CustomText variant="body" mt="l">
              It's similar to a personal password, granting you sole authority
              over the cryptocurrency associated with your wallet address.
            </CustomText>

            <CustomText variant="body" mt="l">
              This cryptographic code plays a pivotal role in securing and
              managing your digital assets, ensuring that only you can authorize
              transactions and access your funds.
            </CustomText>
          </>
        );
      }
      case "SeedPhrase": {
        return (
          <>
            <CustomText variant="body" mt="l">
              A seed or recovery phrase, often referred to as a recovery phrase,
              is a vital sequence of words generated by your cryptocurrency
              wallet during its initial setup.
            </CustomText>
            <CustomText variant="body" mt="l">
              This unique phrase serves as a backup key, enabling you to regain
              access to your wallet and its associated funds in case of device
              loss, theft, or forgotten passwords.
            </CustomText>

            <CustomText variant="body" mt="l">
              By securely storing and utilizing your seed phrase, you can ensure
              the protection and accessibility of your digital assets.
            </CustomText>
          </>
        );
      }
      case "Wallet": {
        return (
          <>
            <CustomText variant="body" mt="l">
              A crypto wallet is a digital tool that allows you to store,
              manage, and transact with cryptocurrencies.
            </CustomText>
            <CustomText variant="body" mt="l">
              Think of it as a digital wallet for your digital assets. At its
              core, a crypto wallet securely stores your private keys, which are
              unique codes that grant you access to your cryptocurrency
              holdings.
            </CustomText>

            <CustomText variant="body" mt="l">
              With a crypto wallet, you can send, receive, and trade various
              cryptocurrencies, making it an essential tool for anyone involved
              in the world of digital assets.
            </CustomText>
          </>
        );
      }
    }
  };
  return (
    <FullPageModalWrapper
      isOpen={isOpen}
      onClose={onClose}
      color={
        activeTheme === "dark"
          ? ["#7055FF", "#000000DD"]
          : ["#7055FF", "#FFFFFF"]
      }
    >
      <Box width="100%" height={200} alignItems="center">
        <Image
          source={handleImage()}
          contentFit="contain"
          style={{ width: 200, height: 200 }}
        />
      </Box>
      <Box flex={1}>
        <ScrollView style={{ flexGrow: 1 }}>
          <CustomText variant="header" fontSize={36} mt="l">
            {handleTitle()} ?
          </CustomText>
          {handleBodyText()}
        </ScrollView>
      </Box>
      <Box width="100%" height={60} justifyContent="center" mb="m">
        <CustomButton
          width={"100%"}
          height={56}
          borderRadius={56}
          text="Got it"
          bgColor={theme.colors.primaryColor}
          color={theme.colors.white}
          onPress={() => onClose()}
        />
      </Box>
    </FullPageModalWrapper>
  );
};

export default OnboardingInformationModal;
