import useActiveTheme from "@/hooks/useTheme";
import { Theme } from "@/theme";
import { useTheme } from "@shopify/restyle";
import { Image } from "expo-image";
import React from "react";
import { ScrollView } from "react-native-gesture-handler";
import Box from "../general/Box";
import CustomButton from "../general/CustomButton";
import CustomText from "../general/CustomText";
import FullPageModalWrapper from "./FullPaperModalWrapper";

const WhatIsSeedPhraseModal = ({
  isOpen,
  onClose,
}: {
  isOpen: boolean;
  onClose: () => void;
}) => {
  const theme = useTheme<Theme>();
  const { colorTheme: activeTheme } = useActiveTheme();

  return (
    <FullPageModalWrapper
      isOpen={isOpen}
      onClose={onClose}
      color={
        activeTheme === "dark"
          ? ["#7055FF", "#000000DD"]
          : ["#7055FF", "#FFFFFF"]
      }
    >
      <Box width="100%" height={200} alignItems="center">
        <Image
          source={require("@/assets/images/lock.png")}
          contentFit="contain"
          style={{ width: 200, height: 200 }}
        />
      </Box>
      <Box flex={1}>
        <ScrollView style={{ flexGrow: 1 }}>
          <CustomText variant="header" fontSize={36} mt="l">
            What’s a Seed Phrase ?
          </CustomText>
          <CustomText variant="body" mt="l" textAlign="justify">
            A seed or recovery phrase, often referred to as a recovery phrase,
            is a vital sequence of words generated by your cryptocurrency wallet
            during its initial setup
          </CustomText>
          <CustomText variant="body" mt="l" textAlign="justify">
            This unique phrase serves as a backup key, enabling you to regain
            access to your wallet and its associated funds in case of device
            loss, theft, or forgotten passwords.
          </CustomText>

          <CustomText variant="body" mt="l" textAlign="justify">
            By securely storing and utilizing your seed phrase, you can ensure
            the protection and accessibility of your digital assets.
          </CustomText>
        </ScrollView>
      </Box>
      <Box width="100%" height={60} mb="l" justifyContent="center">
        <CustomButton
          width={"100%"}
          height={56}
          borderRadius={56}
          text="Got it"
          bgColor={theme.colors.primaryColor}
          color={theme.colors.white}
          onPress={() => onClose()}
        />
      </Box>
    </FullPageModalWrapper>
  );
};

export default WhatIsSeedPhraseModal;
